# Generated by Django 5.0.3 on 2024-05-09 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEnergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Tipo de energia', max_length=100, unique=True, verbose_name='Tipo')),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Nome civil de alguem, womp womp', max_length=100, unique=True, verbose_name='Nome')),
                ('email', models.CharField(help_text='Email com atribuição direta ao user, womp womp', max_length=100, unique=True, verbose_name='Email')),
                ('senha', models.CharField(help_text='Senha não criptografada, womp womp', max_length=100, unique=True, verbose_name='Senha')),
                ('dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custoAnterior', models.DecimalField(decimal_places=2, help_text='Preço anterior', max_digits=10, verbose_name='CustoAnterior')),
                ('custoAtual', models.DecimalField(decimal_places=2, help_text='Preço atual', max_digits=10, verbose_name='CustoAtual')),
                ('duracao', models.DecimalField(decimal_places=2, help_text='Jornada', max_digits=10, verbose_name='Duracao')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('energiaAnterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_energia_anterior', to='site_cityhub.typeenergy')),
                ('energiaAtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_energia_atual', to='site_cityhub.typeenergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_cityhub.user')),
            ],
        ),
    ]
