# Generated by Django 5.0.3 on 2024-05-22 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_cityhub', '0002_correlation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='progress',
            field=models.OneToOneField(help_text='Progresso da assinatura', on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='site_cityhub.progress', verbose_name='Progresso'),
        ),
    ]
